// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mrfse
List mrfse(int A, IntegerMatrix sample, double c, int max_degree);
RcppExport SEXP _mrfse_mrfse(SEXP ASEXP, SEXP sampleSEXP, SEXP cSEXP, SEXP max_degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type max_degree(max_degreeSEXP);
    rcpp_result_gen = Rcpp::wrap(mrfse(A, sample, c, max_degree));
    return rcpp_result_gen;
END_RCPP
}
// mrfse_sa
List mrfse_sa(int A, IntegerMatrix sample, double c, double t0, int iterations, int max_degree);
RcppExport SEXP _mrfse_mrfse_sa(SEXP ASEXP, SEXP sampleSEXP, SEXP cSEXP, SEXP t0SEXP, SEXP iterationsSEXP, SEXP max_degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type max_degree(max_degreeSEXP);
    rcpp_result_gen = Rcpp::wrap(mrfse_sa(A, sample, c, t0, iterations, max_degree));
    return rcpp_result_gen;
END_RCPP
}
// mrfse_ci
List mrfse_ci(int A, IntegerMatrix sample, double tau, int max_degree);
RcppExport SEXP _mrfse_mrfse_ci(SEXP ASEXP, SEXP sampleSEXP, SEXP tauSEXP, SEXP max_degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type max_degree(max_degreeSEXP);
    rcpp_result_gen = Rcpp::wrap(mrfse_ci(A, sample, tau, max_degree));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mrfse_mrfse", (DL_FUNC) &_mrfse_mrfse, 4},
    {"_mrfse_mrfse_sa", (DL_FUNC) &_mrfse_mrfse_sa, 6},
    {"_mrfse_mrfse_ci", (DL_FUNC) &_mrfse_mrfse_ci, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mrfse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
