# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mrfse <- function(A, sample, c, max_degree) {
    .Call(`_mrfse_mrfse`, A, sample, c, max_degree)
}

mrfse_sa <- function(A, sample, c, t0, iterations, max_degree) {
    .Call(`_mrfse_mrfse_sa`, A, sample, c, t0, iterations, max_degree)
}

mrfse_ci <- function(A, sample, tau, max_degree) {
    .Call(`_mrfse_mrfse_ci`, A, sample, tau, max_degree)
}

